spring:
  datasource:
    url: jdbc:mysql://j11e101.p.ssafy.io:3307/mydb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profiles:
    active: dev
  config:
    import: "optional:classpath:application-secret.yml"
