spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: { DB_URL }
    username: { DB_USER }
    password: { DB_PWD }
  jpa:
    hibernate:
      ddl-auto: update # 배포 환경에서는 DB 자동 생성 금지
jwt:
  secret: { JWT_SECRET }