spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show_sql: true
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: true
        use_sql_comments: true
