version: "3"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # 호스트의 3000번 포트를 Nginx의 80번 포트로 매핑
    restart: always # 컨테이너가 종료되면 자동으로 재시작
